---
# installing docker 'ce'
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

# docker service variables
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# docker-compose
docker_install_py: true
docker_install_compose: true
docker_compose_version: "1.24.0"
docker_compose_path: /usr/local/bin/docker-compose

#  distributions details 
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true

# A list of users who will be added to the docker group.
docker_users: 
  - vagrant
