- name: Remove {{ container_name }} container
  docker_container:
    name: "{{ container_name }}"
    state: absent
  ignore_errors: yes
  when: docker_remove_service

- name: Run {{ container_name }} container
  docker_container:
    name: "{{ container_name }}"
    restart_policy: always
    hostname: "{{ ansible_hostname }}"
    ports: "{{ container_ports }}"
    memory: 512m
    image: "{{ image_name }}"
    state: started
    env: "{{ environment_var }}"
  register: container_output

- name: Check if container {{ container_name }} running 
  set_fact:
    container_is_running: "{{ container_output.ansible_facts.docker_container.State.Running }}"

- fail:
    msg: "The service is not running"
  when: not container_is_running

- name: Get container {{ container_name }} IP
  set_fact:
    container_ip: "{{ container_output.ansible_facts.docker_container.NetworkSettings.IPAddress }}"

- name: Wait for {{ poll_timeout }}s for container {{ container_name }}
  wait_for:
    host: "{{ container_ip }}"
    port: "{{ poll_port }}"
    timeout: "{{ poll_timeout }}"

