---
- name: Include {{ ansible_os_family }} variables
  include_vars: "{{ ansible_os_family }}.yml"

# TODO: when the nginx.conf updated, 
# - name: Define nginx_user.
#   set_fact:
#     nginx_user: "{{ __nginx_user }}"
#   when: nginx_user is not defined

- include_tasks: ubuntu-setup.yml
  when: ansible_distribution == 'Ubuntu'

# TODO: if need to customize the nginx.conf file 
# - name: Copy the nginx configuration file
#   template:
#     src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
#     validate="/usr/sbin/nginx -t -c %s"
#   notify:
#    - restart nginx


- name: Remove default vhost file
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  when: nginx_remove_default_vhost | default('present')

- name: Copy the new vhost file
  template:
    src: default.j2
    dest: "{{ nginx_vhost_path }}/vhost.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  with_items: "{{ nginx_vhosts }}"
  notify:
    - reload nginx

# TODO better option would be symlink vhost file
# - name: Create the link for site enabled specific configurations
#   file: path=/etc/nginx/sites-enabled/default state=link src=/etc/nginx/sites-available/default

- name: Ensure nginx service 
  service: name=nginx state=started enabled=yes

# - name: Remove default nginx vhost config file (if configured).
#   file:
#     path: "{{ nginx_default_vhost_path }}"
#     state: absent
#   when: nginx_remove_default_vhost
#   notify: restart nginx